### ISSUE TITLE
why preventDefault? on arrow up down

### ISSUE THREAD

**Issue by softmarshmallow** [oaarnikoivu/shadcn-virtualized-combobox#4]
I don't see why commented area is required. it disables the default accesiblity of cmdk, but does not prevent any issues.
If there is a history around this, please share.

```
  const handleKeyDown = (event: React.KeyboardEvent) => {
    // if (event.key === "ArrowDown" || event.key === "ArrowUp") {
    //   event.preventDefault();
    // }
  };
```

Thanks.!

**Comment by oaarnikoivu** [comment]
I wasn't able to get keyboard navigation working at the time, I may update it soon with a fix 👍
